---
abstract: 'Send Log::Any logs to a subroutine'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-Adapter-Callback
requires:
  Log::Any::Adapter::Base: 0
  Log::Any::Adapter::Util: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Log-Any-Adapter-Callback
  homepage: https://metacpan.org/release/Log-Any-Adapter-Callback
  repository: git://github.com/sharyanto/perl-Log-Any-Adapter-Callback.git
version: 0.07
